export const dataCursos = [
    {
        nombre: "Introducción a la IA",
        descripcion: "Aprenda los conceptos básicos de la IA y sus aplicaciones.",
        imagen: "assets/imagenes_cursos/introducion a la IA.jpg",
        profesor: "Dr. Juan Pérez",
        modulos: 3,
        duracion: "18h",
        moudlo1: "Historia y fundamentos de la inteligencia artificial",
        modulo2: "Aplicaciones actuales de la IA",
        modulo3: "Desafíos éticos y el futuro de la IA",
        pro: false
    },
    {
        nombre: "Técnicas avanzadas de IA",
        descripcion: "Profundice en los algoritmos y modelos avanzados de la IA.",
        imagen: "assets/imagenes_cursos/tecnicas avanzadas de IA.jpg",
        profesor: "Dra. Ana Gómez",
        modulos: 3,
        duracion: "48h",
        modulo1:"Aprendizaje profundo y redes neuronales",
        modulo2: "Modelos generativos y transferencia de estilo",
        modulo3: "Implementación de modelos en producción",
        pro: true
    },
    {
        nombre: "Ética y Sociedad",
        descripcion: "Explora las implicaciones éticas y sociales de la inteligencia artificial.",
        imagen: "assets/imagenes_cursos/Etica y sociedad de la IA.png",
        profesor: "Dr. Luis Martínez",
        modulos: 3,
        duracion: "10h",
        modulo1: "Principios éticos de la inteligencia artificial",
        modulo2: "Sesgos algorítmicos e impacto social",
        modulo3: "Regulación y gobernanza de la IA",
        pro: false
    },
    {
        nombre: "Transformación Digital",
        descripcion: "Descubre cómo la tecnología está cambiando los modelos de negocio y la sociedad.",
        imagen: "assets/imagenes_cursos/IA en los negocios.jpg",
        profesor: "Dra. Laura Fernández",
        modulos: 3,
        duracion: "15h",
        modulo1: "Qué es la transformación digital",
        modulo2: "Tecnología como motor de cambio",
        modulo3: "Liderazgo y adaptación al cambio",
        pro: false
    },
    {
        nombre: "Fundamentos para Principiantes",
        descripcion: "Un curso introductorio para quienes inician en el mundo de la tecnología y la IA.",
        imagen: "assets/imagenes_cursos/IA para principiantes.jpeg",
        profesor: "Dr. Carlos López",
        modulos: 3,
        duracion: "7h",
        modulo1: "Introducción a la computación",
        modulo2: "Pensamiento lógico y programación básica",
        modulo3: "Primeros pasos con IA y datos",
        pro: false
    },
    {
        nombre: "Gestión de Proyectos Tecnológicos",
        descripcion: "Aprende a planificar y gestionar proyectos tecnológicos de manera efectiva.",
        imagen: "assets/imagenes_cursos/gestion de proyectos de IA.jpg",
        profesor: "Dra. María Rodríguez",
        modulos: 3,
        duracion: "15h",
        modulo1: "Fundamentos de gestión de proyectos",
        modulo2: "Metodologías ágiles y tradicionales",
        modulo3: "Gestión de equipos y entrega de valor",
        pro: false
    },
    {
        nombre: "Data Science",
        descripcion: "Descubre cómo analizar datos y obtener información valiosa para la toma de decisiones.",
        imagen: "assets/imagenes_cursos/IA y data science.jpg",
        profesor: "Dr. Andrés Torres",
        modulos: 3,
        duracion: "22h",
        modulo1: "Introducción al análisis de datos",
        modulo2: "Estadística y visualización de datos",
        modulo3: "Introducción al aprendizaje automático",
        pro: true
    },
    {
        nombre: "Tecnología en Salud",
        descripcion: "Explora el impacto de la tecnología en la industria de la salud y la medicina.",
        imagen: "assets/imagenes_cursos/IA en Healthcare.jpg",
        profesor: "Dra. Elena Ruiz",
        modulos: 3,
        duracion: "17h",
        modulo1: "Fundamentos de la salud digital",
        modulo2: "Aplicaciones de IA en medicina",
        modulo3: "Ética y regulaciones en tecnología médica",
        pro: false
    },
    {
        nombre: "Tecnología en Finanzas",
        descripcion: "Comprende el papel de la tecnología en el sector financiero y la innovación en servicios.",
        imagen: "assets/imagenes_cursos/IA y finanzas.jpg",
        profesor: "Dr. Javier Sánchez",
        modulos: 3,
        duracion: "14h",
        modulo1: "FinTech y evolución del sistema financiero",
        modulo2: "Inteligencia artificial y big data en finanzas",
        modulo3: "Ciberseguridad y regulación financiera",
        pro: false
    },
    {
        nombre: "Marketing Digital",
        descripcion: "Aprovecha las herramientas digitales para potenciar estrategias de marketing.",
        imagen: "assets/imagenes_cursos/IA y marketing.jpg",
        profesor: "Dra. Paula Jiménez",
        modulos: 3,
        duracion: "11h",
        modulo1: "Estrategia de marketing en entornos digitales",
        modulo2: "Publicidad y posicionamiento en buscadores",
        modulo3: "Analítica digital y optimización de campañas",
        pro: false
    },
    {
        nombre: "Tecnología en Educación",
        descripcion: "Aplica herramientas tecnológicas para mejorar procesos de enseñanza y aprendizaje.",
        imagen: "assets/imagenes_cursos/IA y eduacion.jpg",
        profesor: "Dr. Roberto Castro",
        modulos: 2,
        duracion: "10h",
        modulo1: "Herramientas y plataformas de enseñanza virtual",
        modulo2: "Analítica del aprendizaje y personalización",
        pro: false
    },
    {
        nombre: "Tecnología y Sostenibilidad",
        descripcion: "Utiliza la tecnología para impulsar soluciones sostenibles y cuidar el medio ambiente.",
        imagen: "assets/imagenes_cursos/IA y sostenibilidad.jpg",
        profesor: "Dra. Sofía Herrera",
        modulos: 3,
        duracion: "12h",
        modulo1: "Innovaciones tecnológicas para el desarrollo sostenible",
        modulo2: "Monitoreo ambiental y uso de datos geoespaciales",
        modulo3: "Economía circular y responsabilidad tecnológica",
        pro: false
    },
    {
        nombre: "Fundamentos de IA",
        descripcion: "Aprenda los conceptos básicos de la IA y sus aplicaciones.",
        imagen: "assets/imagenes_cursos/Fundamentos de IA.jpg",
        profesor: "Dr. German Gonzalez",
        modulos: 2,
        duracion: "7h",
        modulo1: "Conceptos esenciales y tipos de inteligencia artificial",
        modulo2: "Herramientas y entornos de desarrollo en IA",
        pro: false
    },
    {
        nombre: "Fundamentos de Machine Learning",
        descripcion: "Introducción a los algoritmos y técnicas de machine learning.",
        imagen: "assets/imagenes_cursos/Fundamentos de machine learning.jpg",
        profesor: "Dra. Ana Torres",
        modulos: 3,
        duracion: "19h",
        modulo1: "Introducción al aprendizaje automático",
        modulo2: "Algoritmos clásicos y cómo aplicarlos",
        modulo3: "Evaluación de modelos y ajuste de parámetros",
        pro: true
    },
    {
        nombre: "Fundamentos de Deep Learning",
        descripcion: "Explore los conceptos centrales de deep learning.",
        imagen: "assets/imagenes_cursos/Fundamentos de deep learning.jpg",
        profesor: "Dr. Juan Carlos",
        modulos: 4,
        duracion: "19h",
        modulo1: "Redes neuronales artificiales y perceptrón multicapa",
        modulo2: "Redes convolucionales (CNN) y visión artificial",
        modulo3: "Técnicas de regularización y mejora de modelos",
        pro: true
    },
    {
        nombre: "Procesamiento de Lenguaje Natural",
        descripcion: "Comprende cómo procesar y analizar el lenguaje humano con tecnología.",
        imagen: "assets/imagenes_cursos/procesamiento de natural language.jpg",
        profesor: "Dra. Laura Martínez",
        modulos: 3,
        duracion: "12h",
        modulo1: "Representación y limpieza de texto",
        modulo2: "Modelos de lenguaje y word embeddings",
        modulo3: "Aplicaciones prácticas de NLP",
        pro: true
    },
    {
        nombre: "Visión por Computadora",
        descripcion: "Introducción a la visión artificial y al reconocimiento de imágenes.",
        imagen: "assets/imagenes_cursos/computer-vision.png",
        profesor: "Dr. Joel Torres",
        modulos: 3,
        duracion: "12h",
        modulo1: "Fundamentos del procesamiento de imágenes digitales",
        modulo2: "Detección y clasificación de objetos",
        modulo3: "Segmentación, seguimiento y análisis avanzado",
        pro: true
    }
];